import type { CccRecord, CccInteraction, ActivityLogEntry } from "@/lib/cccWriter"

// ── Demo Customers ───────────────────────────────────────────────

export const DEMO_CUSTOMERS: (CccRecord & { id: string; created_at: string })[] = [
  {
    id: "demo-meridian-001",
    created_at: "2026-04-01T10:15:00Z",
    email: "sarah@meridianretail.com",
    name: "Sarah Chen",
    company: "Meridian Retail Co.",
    role: "CFO / Finance Lead",
    revenue_range: "$50M-$150M",
    lifecycle_stage: "sales",
    last_interaction_at: "2026-04-08T14:45:00Z",
    last_agent_id: "contribution-margin",
    last_agent_title: "Contribution Margin",
    total_sessions: 3,
    total_turns: 32,
    highest_intent_score: 7,
    booking_requested: true,
    demo_components_shown: ["waterfall_chart", "channel_table", "cohort_heatmap"],
    primary_use_case: "Contribution Margin",
    pain_points: ["Cannot see true margin by SKU", "Manual Excel reconciliation takes 2 days/month", "CAC attribution across DTC and wholesale unclear"],
    topics_discussed: ["SKU-level margin", "CAC by channel", "DTC vs wholesale profitability", "UK expansion data needs"],
  },
  {
    id: "demo-techbrands-002",
    created_at: "2026-04-03T09:30:00Z",
    email: "mike@techbrands.io",
    name: "Mike Torres",
    company: "TechBrands Inc",
    role: "COO / VP Operations",
    revenue_range: "$25M-$50M",
    lifecycle_stage: "discovery",
    last_interaction_at: "2026-04-10T14:47:00Z",
    last_agent_id: "cohorts",
    last_agent_title: "Cohorts",
    total_sessions: 2,
    total_turns: 14,
    highest_intent_score: 4,
    booking_requested: false,
    demo_components_shown: ["cohort_heatmap"],
    primary_use_case: "Cohorts",
    pain_points: ["Retention dips after month 3", "Cannot segment cohorts by channel"],
    topics_discussed: ["Repeat purchase rates", "LTV by cohort", "Subscription churn"],
  },
  {
    id: "demo-novacom-003",
    created_at: "2026-03-20T11:00:00Z",
    email: "lisa@novacomglobal.com",
    name: "Lisa Park",
    company: "NovaCom Global",
    role: "CMO / Growth Lead",
    revenue_range: "$15M-$25M",
    lifecycle_stage: "marketing",
    last_interaction_at: "2026-03-27T16:20:00Z",
    last_agent_id: "marketing-sales",
    last_agent_title: "Marketing & Sales Analytics",
    total_sessions: 1,
    total_turns: 5,
    highest_intent_score: 2,
    booking_requested: false,
    demo_components_shown: ["channel_table"],
    primary_use_case: "Marketing & Sales Analytics",
    pain_points: ["Platform-reported ROAS doesn't match actual revenue"],
    topics_discussed: ["ROAS accuracy", "Meta vs Google attribution overlap"],
  },
  {
    id: "demo-pulseretail-004",
    created_at: "2026-04-09T08:45:00Z",
    email: "raj@pulseretail.com",
    name: "Raj Patel",
    company: "Pulse Retail",
    role: "VP Ecommerce",
    revenue_range: "$50M-$150M",
    lifecycle_stage: "discovery",
    last_interaction_at: "2026-04-10T14:45:00Z",
    last_agent_id: "inventory-planning",
    last_agent_title: "Product & Inventory Planning",
    total_sessions: 1,
    total_turns: 9,
    highest_intent_score: 5,
    booking_requested: false,
    demo_components_shown: ["metric_card"],
    primary_use_case: "Product & Inventory Planning",
    pain_points: ["$2M in dead inventory", "Forecasting still in Google Sheets"],
    topics_discussed: ["Stockout risk", "Reorder points", "Demand forecasting"],
  },
  {
    id: "demo-glowlab-005",
    created_at: "2026-04-07T15:30:00Z",
    email: "emma@glowlab.co",
    name: "Emma Liu",
    company: "GlowLab Skincare",
    role: "CEO / Founder",
    revenue_range: "$15M-$25M",
    lifecycle_stage: "sales",
    last_interaction_at: "2026-04-10T11:20:00Z",
    last_agent_id: "saras-agent",
    last_agent_title: "Saras Agent",
    total_sessions: 2,
    total_turns: 18,
    highest_intent_score: 8,
    booking_requested: true,
    demo_components_shown: ["waterfall_chart", "cohort_heatmap", "comparison_table"],
    primary_use_case: "Saras Agent",
    pain_points: ["10 hours/week in spreadsheets", "Fundraise coming up — need data clarity"],
    topics_discussed: ["Full-stack data needs", "Fundraise readiness", "Data infrastructure cost"],
  },
]

// ── Demo Interactions (for Meridian Retail detail page) ──────────

export const DEMO_INTERACTIONS: (CccInteraction & { id: string; created_at: string })[] = [
  {
    id: "int-001",
    created_at: "2026-04-01T10:15:00Z",
    customer_id: "demo-meridian-001",
    lifecycle_stage: "marketing",
    interaction_type: "lead_captured",
    actor_type: "agent",
    actor_name: "Contribution Margin Agent",
    agent_id: "contribution-margin",
    summary: "Sarah Chen from Meridian Retail Co. (CFO, $80M DTC fashion) entered the Contribution Margin agent. Revenue range: $50M-$150M.",
    details: { revenue_range: "$50M-$150M", source: "linkedin_ad" },
    channel: "website",
  },
  {
    id: "int-002",
    created_at: "2026-04-01T10:32:00Z",
    customer_id: "demo-meridian-001",
    lifecycle_stage: "discovery",
    interaction_type: "summary_generated",
    actor_type: "agent",
    actor_name: "Contribution Margin Agent",
    agent_id: "contribution-margin",
    summary: "Sarah engaged for 12 turns. Primary pain: cannot see true margin by SKU — currently spending 2 days/month reconciling in Excel. Interested in waterfall breakdown and CAC attribution. Shown waterfall_chart and channel_table demos. Intent score: 6.",
    details: {
      turn_count: 12,
      intent_score: 6,
      conversation_phase: "handoff",
      topics: ["SKU-level margin", "CAC by channel", "Excel reconciliation"],
      pain_points: ["Cannot see true margin by SKU", "Manual Excel reconciliation"],
      demo_components_shown: ["waterfall_chart", "channel_table"],
      key_quotes: ["We spend 2 days a month reconciling margins in Excel"],
    },
    channel: "website",
  },
  {
    id: "int-003",
    created_at: "2026-04-05T14:20:00Z",
    customer_id: "demo-meridian-001",
    lifecycle_stage: "discovery",
    interaction_type: "summary_generated",
    actor_type: "agent",
    actor_name: "Cohorts Agent",
    agent_id: "cohorts",
    summary: "Sarah returned and explored the Cohorts agent. Discussed DTC repeat purchase rates and LTV by acquisition cohort. Pain: retention dips after month 3 and they cannot identify which cohorts to invest in. Shown cohort_heatmap. Intent score: 7.",
    details: {
      turn_count: 8,
      intent_score: 7,
      topics: ["Repeat purchase rates", "LTV by cohort", "Month-3 retention drop"],
      pain_points: ["Retention dips after month 3", "Cannot identify which cohorts to invest in"],
      demo_components_shown: ["cohort_heatmap"],
    },
    channel: "website",
  },
  {
    id: "int-004",
    created_at: "2026-04-08T14:32:00Z",
    customer_id: "demo-meridian-001",
    lifecycle_stage: "discovery",
    interaction_type: "summary_generated",
    actor_type: "agent",
    actor_name: "Contribution Margin Agent",
    agent_id: "contribution-margin",
    summary: "Third visit. Sarah went deeper on DTC vs wholesale profitability. Discussed UK expansion data needs. Mentioned upcoming board review. Intent score: 7.",
    details: {
      turn_count: 12,
      intent_score: 7,
      conversation_phase: "handoff",
      topics: ["DTC vs wholesale profitability", "UK expansion", "Board review"],
      pain_points: ["Need per-geography margin before UK launch"],
      urgency: "Board review in 3 weeks",
    },
    channel: "website",
  },
  {
    id: "int-005",
    created_at: "2026-04-08T14:45:00Z",
    customer_id: "demo-meridian-001",
    lifecycle_stage: "sales",
    interaction_type: "booking_requested",
    actor_type: "agent",
    actor_name: "Contribution Margin Agent",
    agent_id: "contribution-margin",
    summary: "Sarah from Meridian Retail requested a sales call via the Contribution Margin agent. Third session overall. Consistent high intent across visits.",
    details: { preferred_time: "Next Tuesday afternoon" },
    channel: "website",
  },
]

// ── Demo Activity Feed ───────────────────────────────────────────

function minutesAgo(n: number): string {
  return new Date(Date.now() - n * 60_000).toISOString()
}

export const DEMO_ACTIVITY_FEED: (ActivityLogEntry & { id: string; created_at: string })[] = [
  {
    id: "act-001",
    created_at: minutesAgo(2),
    agent_id: "cohorts",
    agent_title: "Cohorts",
    visitor_name: "Mike Torres",
    company: "TechBrands Inc",
    visitor_role: "COO",
    action_type: "turn_completed",
    action_summary: "Mike in Cohorts — Phase: discovery, Turn 6",
    conversation_phase: "discovery",
    turn_number: 6,
    intent_score: 4,
  },
  {
    id: "act-002",
    created_at: minutesAgo(5),
    agent_id: "contribution-margin",
    agent_title: "Contribution Margin",
    visitor_name: "Raj Patel",
    company: "Pulse Retail",
    visitor_role: "VP Ecommerce",
    action_type: "lead_captured",
    action_summary: "Raj from Pulse Retail (VP Ecommerce) entered Contribution Margin",
    conversation_phase: "arrival",
    turn_number: 1,
    intent_score: 0,
  },
  {
    id: "act-003",
    created_at: minutesAgo(9),
    agent_id: "marketing-sales",
    agent_title: "Marketing & Sales Analytics",
    action_type: "turn_completed",
    action_summary: "Anonymous visitor in Marketing & Sales — Phase: topic_entry, Turn 3",
    conversation_phase: "topic_entry",
    turn_number: 3,
    intent_score: 1,
  },
  {
    id: "act-004",
    created_at: minutesAgo(12),
    agent_id: "saras-agent",
    agent_title: "Saras Agent",
    visitor_name: "Emma Liu",
    company: "GlowLab Skincare",
    visitor_role: "CEO",
    action_type: "booking_requested",
    action_summary: "Emma from GlowLab booked a call via Saras Agent",
    conversation_phase: "handoff",
    turn_number: 14,
    intent_score: 8,
  },
  {
    id: "act-005",
    created_at: minutesAgo(18),
    agent_id: "data-warehousing",
    agent_title: "Data Warehousing",
    visitor_name: "Sarah Chen",
    company: "Meridian Retail",
    visitor_role: "CFO",
    action_type: "summary_generated",
    action_summary: "Conversation with Sarah completed (14 turns, intent: 7)",
    conversation_phase: "handoff",
    turn_number: 14,
    intent_score: 7,
  },
  {
    id: "act-006",
    created_at: minutesAgo(25),
    agent_id: "pipelines",
    agent_title: "Pipelines",
    visitor_name: "Alex Kim",
    company: "VoltThread",
    visitor_role: "Head of Data",
    action_type: "demo_shown",
    action_summary: "Alex was shown flow_diagram in Pipelines",
    conversation_phase: "discovery",
    turn_number: 5,
    intent_score: 3,
    demo_component: "flow_diagram",
  },
  {
    id: "act-007",
    created_at: minutesAgo(32),
    agent_id: "inventory-planning",
    agent_title: "Product & Inventory Planning",
    visitor_name: "Raj Patel",
    company: "Pulse Retail",
    action_type: "turn_completed",
    action_summary: "Raj in Inventory Planning — Phase: discovery, Turn 7",
    conversation_phase: "discovery",
    turn_number: 7,
    intent_score: 5,
  },
  {
    id: "act-008",
    created_at: minutesAgo(40),
    agent_id: "saras-iq",
    agent_title: "Saras iQ",
    visitor_name: "David Nguyen",
    company: "Harlow Home",
    visitor_role: "VP Analytics",
    action_type: "lead_captured",
    action_summary: "David from Harlow Home entered Saras iQ",
    conversation_phase: "arrival",
    turn_number: 1,
    intent_score: 0,
  },
]
